type Transacao {
  id : Int
  descricao : String
  valor : Float
  confirmado : Boolean
  data : String
  remetente : User
  destinatario : User
}

type Query {
  transacoesUsuario(quant : Int!, pesquisa : String) : [Transacao]
  transacoesComUsuario(idUsuario : Int) : [Transacao]
  findTransacao(idTransacao : Int) : Transacao
}

input TransacaoInput {
  descricao : String, 
  valor : Float!,
  idReceptor : Int!,
  data : String
}

type Mutation {
  realizarTransacao(data : TransacaoInput) : Transacao
  confirmarTransacao(idTransacao : Int) : Transacao
}