type User {
  id : Int
  nome : String
  email : String
  perfil : String
}

input CreateUserInput {
  nome : String!
  email : String!
}

input UpdateUserInput {
  nome : String
  email : String
}

input UsuarioLogadoInput{
  id : Int
  nome : String
  email : String
  perfil : String
}

type Query {
  usuarios : [User]
  usuario(id : Int) : User
  pesquisaUsuario(pesquisa : String) : [User]
}

type Mutation {
  cadastrarUsuario(data : CreateUserInput, userName : String, senha : String) : String
  atualizarUsuario(id : Int!, data : UpdateUserInput) : User!
  deletarUsuario(id : Int!) : Boolean
  editarSenha(id : Int!, senha : String) : User
  logar(userName : String, senha : String) : String
}
