type Contato {
  id : Int
  confirmado : Boolean
  lembretes : [Lembrete]
  outroUsuario : User
  saldoComUsuario : Float
}

type Query {
  contatosUsuario : [Contato]
  procurarContato(pesquisa : String) : [Contato]
}

input ContatoInput {
  idUsuario1 : Int,
  idUsuario2 : Int,
  nomeUsuario1 : String
  descricao : String
}

type Mutation {
  confirmarContato(idContato : Int) : Contato
  negarContato(idContato : Int) : Boolean
  adcionarContato(data : ContatoInput) : Contato
}